server:
  address: 8850
host: 127.0.0.1
spring:
  application:
    name: booking-config
  # Redis 配置
  redis:
    database: 1
    host: ${host}
    port: 6379
    timeout: 2000ms
    password:
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池的最大数据库连接数
        max-active: 5
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  # Nacos配置
  cloud:
    nacos:
      config:
        server-addr: ${host}:8848
        group: DEFAULT_GROUP
        file-extension: yaml
        shared-configs:
          - data-id: application.yaml
            group: DEFAULT_GROUP
  config:
    import: nacos:application-booking.yaml?refresh=true

# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
