host: 127.0.0.1
spring:
  application:
    name: common-module
  # Redis 配置
  redis:
    database: 1
    host: ${host}
    port: 6379
    timeout: 2000ms
    password:
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池的最大数据库连接数
        max-active: 5
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1